name: Deployment

on:
  push:
    tags:
      - "*"

jobs:
  check-cache-exist:
    name: Check cache exist
    runs-on: [self-hosted, macOS]
    outputs:
      status: ${{ steps.is-exist-cache.outcome }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Check exist cache
        id: is-exist-cache
        continue-on-error: true
        run: bash .github/scripts/check_cache_exist.sh

      - name: Xcode Select Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3'